### ISSUE TITLE
Reduce the impact of MimeDB on JS size

### ISSUE THREAD

**Issue by cquiroz** [http4s/http4s-dom#30]
We are testing http4s for our scala.js browser app and it seems to produce a fairly big increase on the scala.js produced by scala.js. One of the contributors is the very large `MimeDB` which maybe not needed on the typical frontend app

Should we split `MimeDB` into jvm and js versions, with the latter having a minimal or empty set of mime types?

**Comment by keynmol** [comment]
If I'm reading this right, it takes ~3 seconds to even parse the output of `fastOptJS`: 
![image](https://user-images.githubusercontent.com/1052965/160594746-f48d5475-9f33-4256-8783-0c2fe3ab2704.png)

Which makes it sort of unusable for development, as both the re-linking and reloading in the browser take a long time

Vanilla app can be dropped down to 2.5MB with fullOptJS, but it has zero to none http4s logic. But fastOptJS produces a 14MB on an app that has very little apart from http4s itself

**Comment by armanbilge** [comment]
Yeah, thanks for this. The stupid large MimeDB that we get from http4s is the source of lots of problems including https://github.com/http4s/http4s-dom/issues/119.

So, yeah, time to fix this.

**Comment by armanbilge** [comment]
I've PRed a fix upstream in https://github.com/http4s/http4s/pull/6211.
